package com.bluetoothpad.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light scheme (teal primary, violet secondary) ────────────────────────────
val md_light_primary                = Color(0xFF1F6F5C)
val md_light_onPrimary              = Color(0xFFFFFFFF)
val md_light_primaryContainer       = Color(0xFFA7F3D8)
val md_light_onPrimaryContainer     = Color(0xFF00201A)
val md_light_secondary              = Color(0xFF7A5BC7)
val md_light_onSecondary            = Color(0xFFFFFFFF)
val md_light_secondaryContainer     = Color(0xFFE9DDFF)
val md_light_onSecondaryContainer   = Color(0xFF22005D)
val md_light_tertiary               = Color(0xFFB5385F)
val md_light_onTertiary             = Color(0xFFFFFFFF)
val md_light_tertiaryContainer      = Color(0xFFFFD9E2)
val md_light_onTertiaryContainer    = Color(0xFF3E001B)
val md_light_error                  = Color(0xFFB3261E)
val md_light_onError                = Color(0xFFFFFFFF)
val md_light_errorContainer         = Color(0xFFF9DEDC)
val md_light_onErrorContainer       = Color(0xFF410E0B)
val md_light_background             = Color(0xFFF7F4EF)
val md_light_onBackground           = Color(0xFF1B1C1A)
val md_light_surface                = Color(0xFFF7F4EF)
val md_light_onSurface              = Color(0xFF1B1C1A)
val md_light_onSurfaceVariant       = Color(0xFF44483F)
val md_light_outline                = Color(0xFF74796F)
val md_light_outlineVariant         = Color(0xFFC5C8BD)
val md_light_surfaceContainer       = Color(0xFFEBE8E1)
val md_light_surfaceContainerHigh   = Color(0xFFE5E2DB)
val md_light_surfaceContainerLow    = Color(0xFFF1EEE8)
val md_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_light_inverseSurface         = Color(0xFF30312E)
val md_light_inverseOnSurface       = Color(0xFFF2F0E9)
val md_light_inversePrimary         = Color(0xFF7FDCC4)

// ── Dark scheme ──────────────────────────────────────────────────────────────
val md_dark_primary                 = Color(0xFF7FDCC4)
val md_dark_onPrimary               = Color(0xFF00382F)
val md_dark_primaryContainer        = Color(0xFF005142)
val md_dark_onPrimaryContainer      = Color(0xFFA7F3D8)
val md_dark_secondary               = Color(0xFFCFBCFF)
val md_dark_onSecondary             = Color(0xFF1E0562)
val md_dark_secondaryContainer      = Color(0xFF4A378E)
val md_dark_onSecondaryContainer    = Color(0xFFE9DDFF)
val md_dark_tertiary                = Color(0xFFFFB1C4)
val md_dark_onTertiary              = Color(0xFF5E112B)
val md_dark_tertiaryContainer       = Color(0xFF8B2047)
val md_dark_onTertiaryContainer     = Color(0xFFFFD9E2)
val md_dark_error                   = Color(0xFFF2B8B5)
val md_dark_onError                 = Color(0xFF601410)
val md_dark_errorContainer          = Color(0xFF8C1D18)
val md_dark_onErrorContainer        = Color(0xFFF9DEDC)
val md_dark_background              = Color(0xFF111311)
val md_dark_onBackground            = Color(0xFFE2E3DE)
val md_dark_surface                 = Color(0xFF111311)
val md_dark_onSurface               = Color(0xFFE2E3DE)
val md_dark_onSurfaceVariant        = Color(0xFFC2C8BB)
val md_dark_outline                 = Color(0xFF8C9287)
val md_dark_outlineVariant          = Color(0xFF44483F)
val md_dark_surfaceContainer        = Color(0xFF1C1F1D)
val md_dark_surfaceContainerHigh    = Color(0xFF262927)
val md_dark_surfaceContainerLow     = Color(0xFF181B19)
val md_dark_surfaceContainerLowest  = Color(0xFF0A0D0B)
val md_dark_inverseSurface          = Color(0xFFE2E3DE)
val md_dark_inverseOnSurface        = Color(0xFF2F3330)
val md_dark_inversePrimary          = Color(0xFF1F6F5C)

// ── AMOLED scheme (pure black surfaces) ─────────────────────────────────────
val md_amoled_primary               = Color(0xFF7FDCC4)
val md_amoled_onPrimary             = Color(0xFF00382F)
val md_amoled_primaryContainer      = Color(0xFF005142)
val md_amoled_onPrimaryContainer    = Color(0xFFA7F3D8)
val md_amoled_secondary             = Color(0xFFCFBCFF)
val md_amoled_onSecondary           = Color(0xFF1E0562)
val md_amoled_secondaryContainer    = Color(0xFF2E1C72)
val md_amoled_onSecondaryContainer  = Color(0xFFE9DDFF)
val md_amoled_tertiary              = Color(0xFFFFB1C4)
val md_amoled_onTertiary            = Color(0xFF5E112B)
val md_amoled_tertiaryContainer     = Color(0xFF6A0F35)
val md_amoled_onTertiaryContainer   = Color(0xFFFFD9E2)
val md_amoled_error                 = Color(0xFFF2B8B5)
val md_amoled_onError               = Color(0xFF601410)
val md_amoled_errorContainer        = Color(0xFF5C0E0A)
val md_amoled_onErrorContainer      = Color(0xFFF9DEDC)
val md_amoled_background            = Color(0xFF000000)
val md_amoled_onBackground          = Color(0xFFEDEDE8)
val md_amoled_surface               = Color(0xFF000000)
val md_amoled_onSurface             = Color(0xFFEDEDE8)
val md_amoled_onSurfaceVariant      = Color(0xFFB8BDB1)
val md_amoled_outline               = Color(0xFF6E7569)
val md_amoled_outlineVariant        = Color(0xFF2A2D28)
val md_amoled_surfaceContainer      = Color(0xFF0B0B0B)
val md_amoled_surfaceContainerHigh  = Color(0xFF141414)
val md_amoled_surfaceContainerLow   = Color(0xFF060606)
val md_amoled_surfaceContainerLowest= Color(0xFF000000)
val md_amoled_inverseSurface        = Color(0xFFEDEDE8)
val md_amoled_inverseOnSurface      = Color(0xFF1C1C1C)
val md_amoled_inversePrimary        = Color(0xFF1F6F5C)

// ── Status indicators ────────────────────────────────────────────────────────
val StatusConnected  = Color(0xFF2E7D32)
val StatusConnecting = Color(0xFFF57F17)
val StatusError      = Color(0xFFB71C1C)

// ── Controller screen (always dark) ─────────────────────────────────────────
val ControllerBg   = Color(0xFF111318)
val BtnPrimary     = Color(0xFF1E2A3A)
val BtnSecondary   = Color(0xFF162032)
val BtnDisconnect  = Color(0xFF8B0000)
val StickBase      = Color(0xFF162032)
val StickKnob      = Color(0xFF3D5A80)
val DpadNormal     = Color(0xFF3D5A80)
val DpadPressed    = Color(0xFF7FDCC4)

val BtnA = Color(0xFF1B5E20)
val BtnB = Color(0xFFB71C1C)
val BtnX = Color(0xFF0D47A1)
val BtnY = Color(0xFFF57F17)

// ── Overlay pill background ──────────────────────────────────────────────────
val OverlayPill      = Color(0x8C000000)
val OverlayPillLight = Color(0x73000000)

// ── Editor UI accents ────────────────────────────────────────────────────────
val EditorSelected = Color(0xFFFFEB3B)
val EditorSave     = Color(0xFF69F0AE)
val EditorDelete   = Color(0xFFFF6B6B)

// ── On-controller text ───────────────────────────────────────────────────────
val ControllerOnBtn = Color(0xFFFFFFFF)
val StickLabel      = Color(0x66FFFFFF)
